port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090

proxies:
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½9929-DV, server: mdv.162899.xyz, port: 8002, type: vmess, uuid: 9fbd489a-e738-4896-b8a9-8b2ad0da3af8, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /9fbd489a-e738-4896-b8a9-8b2ad0da3af8, headers: {Host: mdv.162899.xyz}}}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½9929-CF, server: mdv2.162899.xyz, port: 443, type: vmess, uuid: 9fbd489a-e738-4896-b8a9-8b2ad0da3af8, alterId: 0, cipher: auto, tls: true, network: ws, ws-opts: {path: /9fbd489a-e738-4896-b8a9-8b2ad0da3af8, headers: {Host: mdv.162899.xyz}}}

proxy-groups:
  - name: ğŸš€ å…¨çƒåŠ é€Ÿ
    type: select
    proxies:
      - DIRECT
      - ğŸ‡ºğŸ‡¸ ç¾å›½9929-DV
      - ğŸ‡ºğŸ‡¸ ç¾å›½9929-CF
  - name: ğŸ¯ å›½å†…ç›´è¿
    type: select
    proxies:
      - DIRECT
      - ğŸš€ å…¨çƒåŠ é€Ÿ
  - name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - ğŸ¯ å›½å†…ç›´è¿
      - ğŸš€ å…¨çƒåŠ é€Ÿ
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ å…¨çƒåŠ é€Ÿ
      - ğŸ¯ å›½å†…ç›´è¿

rule-providers:
  RejectAD:
    type: http
    behavior: domain
    url: "https://ghp.162899.xyz/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  ProxyLite:
    type: http
    behavior: domain
    url: "https://ghp.162899.xyz/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxylite.yaml
    interval: 86400
  DirectCN:
    type: http
    behavior: domain
    url: "https://ghp.162899.xyz/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/directcn.yaml
    interval: 86400
  Proxy-fix:
    type: http
    behavior: classical
    url: "https://ghp.162899.xyz/https://raw.githubusercontent.com/rodingbaba/proxy-rule/main/clash/proxy-fix.yaml"
    path: ./ruleset/proxy-fix.yaml
    interval: 86400    
  Direct-fix:
    type: http
    behavior: classical
    url: "https://ghp.162899.xyz/https://raw.githubusercontent.com/rodingbaba/proxy-rule/main/clash/direct-fix.yaml"
    path: ./ruleset/direct-fix.yaml
    interval: 86400        
    
    
rules:
 - DOMAIN-SUFFIX,ip6-localhost,ğŸ¯ å›½å†…ç›´è¿
 - DOMAIN-SUFFIX,ip6-loopback,ğŸ¯ å›½å†…ç›´è¿
 - DOMAIN-SUFFIX,lan,ğŸ¯ å›½å†…ç›´è¿
 - DOMAIN-SUFFIX,local,ğŸ¯ å›½å†…ç›´è¿
 - DOMAIN-SUFFIX,localhost,ğŸ¯ å›½å†…ç›´è¿
 - IP-CIDR,0.0.0.0/8,ğŸ¯ å›½å†…ç›´è¿,no-resolve
 - IP-CIDR,10.0.0.0/8,ğŸ¯ å›½å†…ç›´è¿,no-resolve
 - IP-CIDR,100.64.0.0/10,ğŸ¯ å›½å†…ç›´è¿,no-resolve
 - IP-CIDR,127.0.0.0/8,ğŸ¯ å›½å†…ç›´è¿,no-resolve
 - IP-CIDR,172.16.0.0/12,ğŸ¯ å›½å†…ç›´è¿,no-resolve
 - IP-CIDR,192.168.0.0/16,ğŸ¯ å›½å†…ç›´è¿,no-resolve
 - IP-CIDR,198.18.0.0/16,ğŸ¯ å›½å†…ç›´è¿,no-resolve
 - IP-CIDR,224.0.0.0/4,ğŸ¯ å›½å†…ç›´è¿,no-resolve
 - IP-CIDR6,::1/128,ğŸ¯ å›½å†…ç›´è¿,no-resolve
 - IP-CIDR6,fc00::/7,ğŸ¯ å›½å†…ç›´è¿,no-resolve
 - IP-CIDR6,fe80::/10,ğŸ¯ å›½å†…ç›´è¿,no-resolve
 - IP-CIDR6,fd00::/8,ğŸ¯ å›½å†…ç›´è¿,no-resolve
 - RULE-SET,RejectAD,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
 - RULE-SET,ProxyLite,ğŸš€ å…¨çƒåŠ é€Ÿ
 - RULE-SET,Proxy-fix,ğŸš€ å…¨çƒåŠ é€Ÿ
 - RULE-SET,Direct-fix,ğŸ¯ å›½å†…ç›´è¿
 - RULE-SET,DirectCN,ğŸ¯ å›½å†…ç›´è¿  
 - GEOIP,CN,ğŸ¯ å›½å†…ç›´è¿
 - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
